FROM arm64v8/ros:jazzy-ros-base
ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS yes

# Install all dependencies
RUN set -x && \
  apt-get update && apt-get upgrade -y && \
  : "basic dependencies" && \
  apt-get install -y -qq \
  build-essential \
  cmake git wget curl \
  usbutils \
  python3-pip \
  python3-setuptools \
  python3-colcon-common-extensions \
  lsb-release \
  libusb-1.0-0 \
  libboost-all-dev \
  libpcap-dev \
  libpcl-dev \
  libyaml-cpp-dev \
  libopencv-dev \
  libeigen3-dev && \
  : "backward-cpp dependencies" && \
  apt-get install -y -qq binutils-dev && \
  : "ros2/camera dependencies" && \
  apt-get install -y -qq \
  ros-${ROS_DISTRO}-rmw-fastrtps-cpp \
  ros-${ROS_DISTRO}-rosbag2-storage-mcap \
  ros-${ROS_DISTRO}-xacro \
  ros-${ROS_DISTRO}-tf2* \
  ros-${ROS_DISTRO}-joint-state-publisher \
  ros-${ROS_DISTRO}-pcl-conversions \
  ros-${ROS_DISTRO}-pluginlib \
  ros-${ROS_DISTRO}-diagnostic-updater \
  ros-${ROS_DISTRO}-teleop-twist-keyboard \
  ros-${ROS_DISTRO}-teleop-twist-joy \
  ros-${ROS_DISTRO}-vision-opencv \
  ros-${ROS_DISTRO}-depthai-ros \
  ros-${ROS_DISTRO}-libg2o && \
  : "remove cache" && \
  rm -rf /var/lib/apt/lists/*

ARG NUM_THREADS=4
ARG CMAKE_INSTALL_PREFIX=/usr/local
ENV CPATH=${CMAKE_INSTALL_PREFIX}/include:${CPATH}
ENV C_INCLUDE_PATH=${CMAKE_INSTALL_PREFIX}/include:${C_INCLUDE_PATH}
ENV CPLUS_INCLUDE_PATH=${CMAKE_INSTALL_PREFIX}/include:${CPLUS_INCLUDE_PATH}
ENV LIBRARY_PATH=${CMAKE_INSTALL_PREFIX}/lib:${LIBRARY_PATH}
ENV LD_LIBRARY_PATH=${CMAKE_INSTALL_PREFIX}/lib:${LD_LIBRARY_PATH}

# ==================== backward-cpp ===========================================
ARG BACKWARD_CPP_COMMIT=5ffb2c879ebdbea3bdb8477c671e32b1c984beaa
WORKDIR /tmp
RUN set -x && \
  git clone https://github.com/bombela/backward-cpp.git && \
  cd backward-cpp && \
  git checkout ${BACKWARD_CPP_COMMIT} && \
  mkdir -p build && \
  cd build && \
  cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX} \
    .. && \
  make -j${NUM_THREADS} && \
  make install && \
  cd /tmp && rm -rf *

# ==================== stella_vslam ===========================================
RUN set -x && \
  git clone --depth 1 --recursive https://github.com/stella-cv/stella_vslam.git && \
  cd stella_vslam && \
  mkdir -p build && cd build && \
  CMAKE_PREFIX_PATH=/opt/ros/${ROS_DISTRO}/lib/cmake cmake .. \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_WITH_PANGOLIN_VIEWER=OFF \
    -DUSE_PANGOLIN_VIEWER=OFF && \
  make -j${NUM_THREADS} && make install && \
  rm -rf CMakeCache.txt CMakeFiles Makefile cmake_install.cmake && \
  chmod -R 777 ./*

# ==================== Build the ros2 workspace ===============================
RUN mkdir -p /ros2_ws/src
WORKDIR /ros2_ws
# COPY slam/stella_vslam_ros src/stella_vslam_ros

# RUN set -x && \
#   : "build ROS2 packages" && \
#   bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; \
#   colcon build --parallel-workers ${NUM_THREADS} --cmake-args \
#     -DUSE_STACK_TRACE_LOGGER=ON"

COPY docker/ros_entrypoint.sh /
COPY docker/fastdds_profile.xml /

RUN chmod +x /ros_entrypoint.sh
ENTRYPOINT [ "/ros_entrypoint.sh" ]