FROM arm64v8/ros:jazzy-ros-base-noble
SHELL [ "/bin/bash" , "-c" ]

# Install system and ROS 2 dependencies
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    python3-colcon-common-extensions \
    python3-pip \
    python3-setuptools \
    build-essential \
    lsb-release \
    libusb-1.0-0 \
    libboost-all-dev \
    libpcap-dev \
    libpcl-dev \
    ros-${ROS_DISTRO}-rmw-fastrtps-cpp \
    ros-${ROS_DISTRO}-xacro \
    ros-${ROS_DISTRO}-tf2* \
    ros-${ROS_DISTRO}-joint-state-publisher \
    ros-${ROS_DISTRO}-pcl-conversions \
    ros-${ROS_DISTRO}-pluginlib \
    ros-${ROS_DISTRO}-diagnostic-updater \
    ros-${ROS_DISTRO}-teleop-twist-keyboard \
    ros-${ROS_DISTRO}-image-transport-plugins \
    ros-${ROS_DISTRO}-cv-bridge \
    ros-${ROS_DISTRO}-vision-msgs \
    ros-${ROS_DISTRO}-depthai-ros \
    # ros-${ROS_DISTRO}-nav2-msgs \
    # ros-${ROS_DISTRO}-nav2-amcl \
    # ros-${ROS_DISTRO}-nav2-map-server \
    # ros-${ROS_DISTRO}-nav2-planner \
    # ros-${ROS_DISTRO}-nav2-bringup \
    # ros-${ROS_DISTRO}-nav2-bt-navigator \
    && rm -rf /var/lib/apt/lists/*

# Create ROS2 workspace
RUN mkdir -p /colcon_ws/src
# COPY ./slam /colcon_ws/src/
COPY ./docker/ros_entrypoint.sh /
COPY ./docker/fastdds_profile.xml /

RUN source /opt/ros/${ROS_DISTRO}/setup.bash && \
    cd /colcon_ws && \
    colcon build --symlink-install 
    # && \
    # rm -rf build/ log/

RUN chmod +x /ros_entrypoint.sh
ENTRYPOINT [ "/ros_entrypoint.sh" ]