name: Firmware Static Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  esp32-analysis:
    name: ESP32 Firmware Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Analysis in Docker
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/app" \
            -w "/app/firmware" \
            espressif/idf:v5.5.2 \
            /bin/bash -c "
              # Fix Git safety
              git config --global --add safe.directory '*' && \
              
              # Install tools inside the container
              apt-get update && apt-get install -y cppcheck clang-tidy && \
              
              # Mock micro-ROS (prevents colcon/git clone errors)
              mkdir -p components/micro_ros_espidf_component/micro_ros_dev/install && \
              touch components/micro_ros_espidf_component/libmicroros.a && \
              mkdir -p components/micro_ros_espidf_component/include && \
              
              # Generate the Compilation Database
              . /opt/esp/idf/export.sh && \
              idf.py reconfigure && \
              
              # Run Makefile linting logic
              make lint
            "
