name: Firmware Static Analysis

on:
  push:
    branches: [ main ]
    paths:
      - 'firmware/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'firmware/**'

jobs:
  esp32-analysis:
    name: ESP32 Firmware Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Firmware Linting in Docker
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/firmware:/app/firmware" \
            -w "/app/firmware" \
            espressif/idf:v5.5.2 \
            /bin/bash -c "
              # Fix Git safety and install tools
              git config --global --add safe.directory '*' && \
              apt-get update && apt-get install -y cppcheck clang-tidy && \
              pip install colcon-common-extensions catkin_pkg lark && \
              
              # Build the project to generate compile_commands.json
              make build && \
              
              # Run Static Analysis
              make tidy-check-ci && make cppcheck
            "
