name: Firmware Static Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  esp32-analysis:
    name: ESP32 Firmware Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Analysis in Docker
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/app" \
            -w "/app/firmware" \
            espressif/idf:v5.5.2 \
            /bin/bash -c "
              # Fix Git safety and install tools
              git config --global --add safe.directory '*' && \
              apt-get update && apt-get install -y cppcheck clang-tidy && \
              
              # Rename the real CMakeLists to hide it and create dummy component
              mv components/micro_ros_espidf_component/CMakeLists.txt components/micro_ros_espidf_component/CMakeLists.txt.bak && \
              echo 'idf_component_register(INCLUDE_DIRS \"include\")' > components/micro_ros_espidf_component/CMakeLists.txt && \
              
              # Generate the Compilation Database
              . /opt/esp/idf/export.sh && \
              idf.py reconfigure && \
              
              # Run linting logic
              make lint
            "
